perguntas = [
         {'titulo': 'Qual a capital do Brasil?',
          'nivel': 'Fácil',
          'opcoes': {'A': 'Brasília', 'B': 'Rio de janeiro', 'C': 'São Paulo', 'D': 'Osasco'},
          'correta': 'A'},
         {'titulo': 'Qual o resultado da operação 5 + 5?',
          'nivel': 'Fácil',
          'opcoes': {'A': '10', 'B': '15', 'C': '20', 'D': '25'},
          'correta': 'A'},
         {'titulo': 'Qual o resultado da operação 57 * 5?',
          'nivel': 'Fácil',
          'opcoes': {'A': '195', 'B': '314', 'C': '285', 'D': '235'},
          'correta': 'C'},
         {'titulo': 'Quando é o feriado da Independência do Brasil?',
          'nivel': 'Fácil',
          'opcoes': {'A': '21 de Abril', 'B': '12 de Outubro', 'C': '07 de Setembro', 'D': '15 de Novembro'},
          'correta': 'C'},
         {'titulo': 'Quantos títulos mundiais o Palmeiras tem?',
          'nivel': 'Fácil',
          'opcoes': {'A': '3', 'B': '4', 'C': '1', 'D': '0'},
          'correta': 'D'},
         {'titulo': 'Qual o nome do presidente do Brasil?',
          'nivel': 'Fácil',
          'opcoes': {'A': 'Jair Bolsonaro', 'B': 'Lula', 'C': 'Dilma', 'D': 'Fernando Henrique'},
          'correta': 'B'},
         {'titulo': 'Qual o nome do maior planeta do sistema solar?',
          'nivel': 'medio',
          'opcoes': {'A': 'Júpiter', 'B': 'Saturno', 'C': 'Urano', 'D': 'Netuno'},
          'correta': 'A'},
         {'titulo': 'Qual destas não é uma linguagem de programação?',
          'nivel': 'medio',
          'opcoes': {'A': 'C++', 'B': 'Python', 'C': 'DogeScript', 'D': 'Shiba'},
          'correta': 'D'},
         {'titulo': 'Qual destes números é primo?',
          'nivel': 'medio',
          'opcoes': {'A': '259', 'B': '85', 'C': '49', 'D': '19'},
          'correta': 'D'},
         {'titulo': 'Qual luas Júpiter tem?',
          'nivel': 'difícil',
          'opcoes': {'A': '79', 'B': '92', 'C': '88', 'D': '54'},
          'correta': 'B'},
        ]